export { default as landingImg } from './landing-img.webp';
export { default as backgroundImg } from './background-img.webp';
export { default as ghostnet } from './ghost-net.webp';
export { default as visa } from './visa.png'
export { default as mastercard } from './mastercard.png'
export { default as apple } from './apple.png'
export { default as google } from './google.png'
export { default as coralRay } from './sunglasses/coral-ray.webp';
export { default as neonReef } from './sunglasses/neon-reef.webp';
export { default as stratos } from './sunglasses/stratos.webp';
export { default as zenith } from './sunglasses/zenith.webp';
export { default as solstice } from './sunglasses/solstice.webp';
export { default as cascade } from './sunglasses/cascade.webp';
export { default as aquaEdge } from './sunglasses/aqua-edge.webp';
export { default as coralEclipse } from './sunglasses/coral-eclipse.webp';
export { default as driftLens } from './sunglasses/drift-lens.webp';
export { default as image71 } from './models/image-71.webp'
export { default as image72 } from './models/image-72.webp'
export { default as image73 } from './models/image-73.webp'
export { default as image75 } from './models/image-75.webp'
export { default as image76 } from './models/image-76.webp'
export { default as image80 } from './models/image-80.webp'
export { default as image81 } from './models/image-81.webp'
export { default as image87 } from './models/image-87.webp'
export { default as image88 } from './models/image-88.webp'
export { default as image89 } from './models/image-89.webp'
export { default as image90 } from './models/image-90.webp'
export { default as image91 } from './models/image-91.webp'