import type { Metadata } from "next";
import "./globals.css";
import { Inter, Syncopate } from 'next/font/google';  
import Home from "./page"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
   subsets: ['latin'],
   styles: ['normal', 'italic'], 
  });

const syncopate = Syncopate({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </head>
      <body className={syncopate.className}>  
        {children}
      </body>
    </html>
  );
}
