import type { Metadata } from "next";
import "./globals.css";
import Home from "../pages/homepage"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </head>
      <body>
        <Home/>
      </body>
    </html>
  );
}
